development:
  adapter: postgresql
  encoding: unicode
  database: bookshelf
  pool: 5
  username: username
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: bookshelf
  pool: 5
  username: username
  password: password
